apiVersion: 1
kind: ConfigMap
metadata:
  name: controlhub-config
  namespace: controlhub
data:
  config.json: |
    {
        "inputs": {
            "webhook": {
                "token": "$env.WEBHOOK_TOKEN",
                "to": ["output"],
            }
        },

        "cron": {
            "boot": {
                "time": "@reboot",
                "data": {
                    "content": "booted up."
                },
                "to": ["output"]
            }
        },

        "outputs": {
            "output": {
                "type": "generic",
                "config": {
                    "url": "$env.WEBHOOK_URL"
                }
            }
        }
    }
  install.sh: |
    #!/bin/sh
    go build -o ./plugins/generic.so -buildmode=plugin ./default_plugins/generic/generic.go
